### ISSUE TITLE
Shugger assumes code lives on github

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/lil_shrugger#381] opened 2018-06-21 21:03 UTC
![screen shot 2018-06-21 at 2 59 09 pm](https://user-images.githubusercontent.com/385234/41745349-e364d39e-7563-11e8-9a0e-af5f299d5c00.png)

https://api.github.com/repos/CuBoulder/geocoder/commits doesn't exist.

Atlas was designed to allow use to use any git repo.  Shrugger should only try to help with the api lookups if the repo's url include github.com/CuBoulder.

**Comment by alexfinnarn** [comment] 2019-03-26 18:13
Only add an element to the array if GH is in the URL: https://github.com/CuBoulder/lil_shrugger/blob/2.x/src/services/github.ts#L83

Add a help note of "Code repository to add not in the CU GitHub account?" with a link to the wiki where a sample payload is given for a code asset telling the user what parts to modify, replace, and send via something like Postman.

**Comment by alexfinnarn** [comment] 2019-03-27 19:00
I think this might have come from editing a code asset? I can't reproduce what is going on here, but the error is pretty trivial. The code that grabs the repos gets all it's information from GitHub so all the git URLs are going to come from that. If it comes up again, more info on how it happened would help to resolve the issue.

It most likely comes from https://github.com/CuBoulder/lil_shrugger/blob/2.x/src/views/Code.vue#L196 when looking up the latest commit for a repo not on GH. 

I don't have time to fix now so I'm closing.

**Closed as completed by alexfinnarn** 2019-03-27 19:00 UTC
Labels: bug
